
services:          
  simple-personal-finance-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=spfuser
      - POSTGRES_PASSWORD=spf@1234
      - POSTGRES_DB=spfdb
    ports:
      - "5432:5432"
    volumes:
      - spf-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 33133:8080
    networks:
      - app-network     

volumes:
  spf-db-data:


networks:
  app-network:
    driver: bridge  
