
services:          
  spf.db:
    image: postgres:latest
    container_name: spf-db
    environment:
      - POSTGRES_USER=spfuser
      - POSTGRES_PASSWORD=spf@1234
      - POSTGRES_DB=spfdb
    ports:
      - "5432:5432"
    volumes:
      - spf-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 33133:8080
    networks:
      - app-network  

  spf.seq:
    image: datalust/seq:latest
    container_name: spf.seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5431:5431
      - 8081:80             

volumes:
  spf-db-data:


networks:
  app-network:
    driver: bridge  
