
services:          
  spf-db:
    image: postgres:latest
    container_name: spf-db
    environment:
      - POSTGRES_USER=spfuser
      - POSTGRES_PASSWORD=spf@1234
      - POSTGRES_DB=spfdb
    ports:
      - "5432:5432"
    volumes:
      - spf-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 33133:8080
    networks:
      - app-network
    depends_on:
      - spf-db     

  spf-seq:
    image: datalust/seq:latest
    container_name: spf-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    networks:
      - app-network
    depends_on:
      - spf-api
      - spf-nginx

  spf-nginx:
    image: nginx:latest
    container_name: spf-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/spf.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - app-network
    depends_on:
      - spf-api
      - cert-generator      

  cert-generator:
    image: emberstack/openssl
    container_name: cert-generator
    volumes:
      - ./certs:/out
    command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /out/your_domain.key -out /out/your_domain.crt -subj "/CN=yourdomain.com"
    networks:
      - app-network            


  spf-api:
    build:
      context: ../src
      dockerfile: ./SimplePersonalFinance.API/Dockerfile
    container_name: spf-api           
    restart: always             
    environment: 
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://+:80
    networks:
      - app-network    
    depends_on:
      - spf-db
                                 

volumes:
  spf-db-data:


networks:
  app-network:
    driver: bridge  
