<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" />
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimplePersonalFinance.Core\SimplePersonalFinance.Core.csproj" />
    <ProjectReference Include="..\SimplePersonalFinance.Shared\SimplePersonalFinance.Shared.csproj" />
  </ItemGroup>

</Project>
