<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimplePersonalFinance.API\SimplePersonalFinance.API.csproj" />
    <ProjectReference Include="..\SimplePersonalFinance.Application\SimplePersonalFinance.Application.csproj" />
    <ProjectReference Include="..\SimplePersonalFinance.Core\SimplePersonalFinance.Core.csproj" />
    <ProjectReference Include="..\SimplePersonalFinance.Infrastructure\SimplePersonalFinance.Infrastructure.csproj" />
    <ProjectReference Include="..\SimplePersonalFinance.Shared\SimplePersonalFinance.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
